### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by fcontijoch** [DVigneault/dv-commandline-utils#24]
Based on the instructions you have outlined, I think you are missing the ITKReview Module in ITK which needs to be turned on.

Otherwise, you get an error on compile due to a missing LabelGeometryImageFilter.h file

**Comment by DVigneault** [comment]
Thank you, good catch.  Addressed here:

https://github.com/DVigneault/dv-commandline-utils/commit/e674314c0120d9d0f75fd338b9f4fa5bca88bfda
