### ISSUE TITLE
Missing utils in compiled files

### ISSUE THREAD

**Issue by fcontijoch** [DVigneault/dv-commandline-utils#26]
I believe the enforce boundary function isn't in the latest compiled files

**Comment by DVigneault** [comment]
Good call--haven't done a release in a while.  I've uploaded fresh binaries for linux here:

https://github.com/DVigneault/dv-commandline-utils/releases/tag/v2018.04.25

I don't have my Mac with me--I'll build/update the OsX binaries shortly.  I'll leave this issue open till then.
