### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by fcontijoch** [DVigneault/dv-commandline-utils#28]
When building the code using your instructions on a Mac (Sierra 10.12.6), I received an error that 'itkLabelGeometryImageFilter.h' file not found

Recompiling ITK with Module_ITKReview ON seemed to do the trick....

**Comment by DVigneault** [comment]
A bit sleep deprived so sorry if I'm mis-reading, but I think the README instructions *do* say to compile with `Module_ITKReview=ON`, no?  This is from the README:

```
$ ccmake ../src \
  -DCMAKE_CXX_STANDARD=14 \
  -DBUILD_TESTING=OFF \
  -DBUILD_EXAMPLES=OFF \
  -DBUILD_SHARED_LIBS=OFF \
  -DITK_USE_SYSTEM_TIFF=ON \
  -DModule_ITKReview=ON \
  -DModule_DVMeshNoise=ON \
  -DModule_IOSTL=ON \
  -DModule_SubdivisionQuadEdgeMesh=ON
```

**Comment by fcontijoch** [comment]
Sorry you're correct. I was looking at the README on my fork (which is out of date)
