### ISSUE TITLE
Installation Bugs

### ISSUE THREAD

**Issue by gabriellecolvert** [DVigneault/dv-commandline-utils#31]
Davis, 

We caught a couple of bugs in the install instructions

1) For MacPorts, we need to also install rapidjson-devel

2) For ITK, we need to enable Module_ITKVTKGlue for the VTK connection to work (and avoid errors related to #include <itkImageToVTKImageFilter.h>)

**Comment by DVigneault** [comment]
Thanks for letting me know!  Does this [1] fix it?

[1] https://github.com/DVigneault/dv-commandline-utils/commit/d0d73ba3a7223e564282bde30c82b57cb66eea0a

**Comment by gabriellecolvert** [comment]
Yes, I think that should work!
