### ISSUE TITLE
add Path to dv-cmd-utils binaries to global PATH

### ISSUE THREAD

**Issue by KunalMGupta** [DVigneault/dv-commandline-utils#38]
Hi, 
A small recommendation. It would be great if you could add the path to the binaries to PATH variable so that we can then access them from everywhere and not just while sitting inside the Developer directory. You can simply add the following in your Dockerfile:

export PATH="/code/bin/:$PATH"

**Comment by DVigneault** [comment]
Great suggestion!  Sorry it took me a while to get around to it, but here's the patch:

https://github.com/DVigneault/dv-commandline-utils/commit/35451645fa4cb024077ba55602ea59223cdf6163
